language: python
rvm:
  - 2.2.0
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python-lxml python-pip
install:
- deactivate
- rvm install 2.2.0
- rvm use 2.2.0
- sudo pip install xml2rfc
script: 
- make ghpages
env:
  global:
  - secure: <insert encrypted GH_TOKEN=blah here>
before_deploy: make submit
deploy:
  provider: releases
  api-key:
    secure: <insert encrypted API key here>
  file:
  - $TRAVIS_TAG.txt
  - $TRAVIS_TAG.html
  - $TRAVIS_TAG.xml
  skip_cleanup: true
  on:
    branch: master
    tags: true
